plugins {
    id 'java'
    id 'application'
}

group = 'jbl'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'jbl.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'jbl.Main'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

run {
    standardInput = System.in
}
